// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-gin-swagger-test/app"
	"go-gin-swagger-test/app/controller"
	"go-gin-swagger-test/app/logger"
	"go-gin-swagger-test/core/usecases"
)

// Injectors from wire.go:

func InitializeService() *app.App {
	persistence := usecases.NewPersistence()
	controllerController := controller.NewController(persistence)
	zapLogger := logger.NewZapLogger()
	appApp := app.NewApp(controllerController, zapLogger)
	return appApp
}
